name: Tests & Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: php-cs-fixer

      - name: Check code style
        run: php-cs-fixer check --diff --no-interaction --ansi

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: phpunit

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Run tests
        run: phpunit --colors=always --order-by=random